package org.clinikraj.model;// default package
// Generated Oct 18, 2013 1:22:29 PM by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ClinicalLab generated by hbm2java
 */
@Entity
@Table(name="clinical_lab"
   
)
public class ClinicalLab  implements java.io.Serializable {


     private Integer labId;
     private Integer client;
     private String createdBy;
     private Date createdDate;
     private String lastUpdatedBy;
     private Date lastUpdatedDate;
     private String labName;
     private String websiteAddress;
     private String emailId;
     private String alternateEmailId;
     private String addressLine1;
     private String addressLine2;
     private String area;
     private Integer postOfficeCode;
     private String city;
     private String district;
     private String state;
     private String country;
     private Long phoneLandline;
     private Long emergencyPhoneNumber;
     private Long phoneMobile;
     private Integer phoneFax;
     private Date startDate;
     private Date endDate;
     private String activeFlag;
     private String deleteFlag;
     private String allowThirdpartyAccess;
     private String remarks;
     private byte[] logo;
    
    public ClinicalLab() {
    }

	
    public ClinicalLab(Integer client, String createdBy, Date createdDate, String lastUpdatedBy, Date lastUpdatedDate, String labName, Date startDate, String activeFlag) {
        this.client = client;
        this.createdBy = createdBy;
        this.createdDate = createdDate;
        this.lastUpdatedBy = lastUpdatedBy;
        this.lastUpdatedDate = lastUpdatedDate;
        this.labName = labName;
        this.startDate = startDate;
        this.activeFlag = activeFlag;
    }
    public ClinicalLab(Integer client, String createdBy, Date createdDate, String lastUpdatedBy, Date lastUpdatedDate, String labName, String websiteAddress, String emailId, String alternateEmailId, String addressLine1, String addressLine2, String area, Integer postOfficeCode, String city, String district, String state, String country, Long phoneLandline, Long emergencyPhoneNumber, Long phoneMobile, Integer phoneFax, Date startDate, Date endDate, String activeFlag, String deleteFlag, String allowThirdpartyAccess, String remarks, byte[] logo, Set users, Set testNormalRangeses, Set testVendors, Set doctors, Set testGroupses, Set patients, Set patientTestOrderses, Set doctorCommisionRates, Set testses, Set testSubgroupses) {
       this.client = client;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
       this.lastUpdatedBy = lastUpdatedBy;
       this.lastUpdatedDate = lastUpdatedDate;
       this.labName = labName;
       this.websiteAddress = websiteAddress;
       this.emailId = emailId;
       this.alternateEmailId = alternateEmailId;
       this.addressLine1 = addressLine1;
       this.addressLine2 = addressLine2;
       this.area = area;
       this.postOfficeCode = postOfficeCode;
       this.city = city;
       this.district = district;
       this.state = state;
       this.country = country;
       this.phoneLandline = phoneLandline;
       this.emergencyPhoneNumber = emergencyPhoneNumber;
       this.phoneMobile = phoneMobile;
       this.phoneFax = phoneFax;
       this.startDate = startDate;
       this.endDate = endDate;
       this.activeFlag = activeFlag;
       this.deleteFlag = deleteFlag;
       this.allowThirdpartyAccess = allowThirdpartyAccess;
       this.remarks = remarks;
       this.logo = logo;
       
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="LAB_ID", unique=true, nullable=false)
    public Integer getLabId() {
        return this.labId;
    }
    
    public void setLabId(Integer labId) {
        this.labId = labId;
    }


    @Column(name="CLIENT_ID", nullable=false)
    public Integer getClient() {
        return this.client;
    }
    
    public void setClient(Integer client) {
        this.client = client;
    }

    
    @Column(name="CREATED_BY", nullable=false, length=60)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", nullable=false, length=19)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="LAST_UPDATED_BY", nullable=false, length=60)
    public String getLastUpdatedBy() {
        return this.lastUpdatedBy;
    }
    
    public void setLastUpdatedBy(String lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LAST_UPDATED_DATE", nullable=false, length=19)
    public Date getLastUpdatedDate() {
        return this.lastUpdatedDate;
    }
    
    public void setLastUpdatedDate(Date lastUpdatedDate) {
        this.lastUpdatedDate = lastUpdatedDate;
    }

    
    @Column(name="LAB_NAME", nullable=false, length=60)
    public String getLabName() {
        return this.labName;
    }
    
    public void setLabName(String labName) {
        this.labName = labName;
    }

    
    @Column(name="WEBSITE_ADDRESS", length=60)
    public String getWebsiteAddress() {
        return this.websiteAddress;
    }
    
    public void setWebsiteAddress(String websiteAddress) {
        this.websiteAddress = websiteAddress;
    }

    
    @Column(name="EMAIL_ID", length=100)
    public String getEmailId() {
        return this.emailId;
    }
    
    public void setEmailId(String emailId) {
        this.emailId = emailId;
    }

    
    @Column(name="ALTERNATE_EMAIL_ID", length=100)
    public String getAlternateEmailId() {
        return this.alternateEmailId;
    }
    
    public void setAlternateEmailId(String alternateEmailId) {
        this.alternateEmailId = alternateEmailId;
    }

    
    @Column(name="ADDRESS_LINE1", length=60)
    public String getAddressLine1() {
        return this.addressLine1;
    }
    
    public void setAddressLine1(String addressLine1) {
        this.addressLine1 = addressLine1;
    }

    
    @Column(name="ADDRESS_LINE2", length=60)
    public String getAddressLine2() {
        return this.addressLine2;
    }
    
    public void setAddressLine2(String addressLine2) {
        this.addressLine2 = addressLine2;
    }

    
    @Column(name="AREA", length=60)
    public String getArea() {
        return this.area;
    }
    
    public void setArea(String area) {
        this.area = area;
    }

    
    @Column(name="POST_OFFICE_CODE")
    public Integer getPostOfficeCode() {
        return this.postOfficeCode;
    }
    
    public void setPostOfficeCode(Integer postOfficeCode) {
        this.postOfficeCode = postOfficeCode;
    }

    
    @Column(name="CITY", length=60)
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }

    
    @Column(name="DISTRICT", length=60)
    public String getDistrict() {
        return this.district;
    }
    
    public void setDistrict(String district) {
        this.district = district;
    }

    
    @Column(name="STATE", length=60)
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }

    
    @Column(name="COUNTRY", length=60)
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }

    
    @Column(name="PHONE_LANDLINE")
    public Long getPhoneLandline() {
        return this.phoneLandline;
    }
    
    public void setPhoneLandline(Long phoneLandline) {
        this.phoneLandline = phoneLandline;
    }

    
    @Column(name="EMERGENCY_PHONE_NUMBER")
    public Long getEmergencyPhoneNumber() {
        return this.emergencyPhoneNumber;
    }
    
    public void setEmergencyPhoneNumber(Long emergencyPhoneNumber) {
        this.emergencyPhoneNumber = emergencyPhoneNumber;
    }

    
    @Column(name="PHONE_MOBILE")
    public Long getPhoneMobile() {
        return this.phoneMobile;
    }
    
    public void setPhoneMobile(Long phoneMobile) {
        this.phoneMobile = phoneMobile;
    }

    
    @Column(name="PHONE_FAX")
    public Integer getPhoneFax() {
        return this.phoneFax;
    }
    
    public void setPhoneFax(Integer phoneFax) {
        this.phoneFax = phoneFax;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="START_DATE", nullable=false, length=10)
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="END_DATE", length=10)
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    
    @Column(name="ACTIVE_FLAG", nullable=false, length=1)
    public String getActiveFlag() {
        return this.activeFlag;
    }
    
    public void setActiveFlag(String activeFlag) {
        this.activeFlag = activeFlag;
    }

    
    @Column(name="DELETE_FLAG", length=1)
    public String getDeleteFlag() {
        return this.deleteFlag;
    }
    
    public void setDeleteFlag(String deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    
    @Column(name="ALLOW_THIRDPARTY_ACCESS", length=1)
    public String getAllowThirdpartyAccess() {
        return this.allowThirdpartyAccess;
    }
    
    public void setAllowThirdpartyAccess(String allowThirdpartyAccess) {
        this.allowThirdpartyAccess = allowThirdpartyAccess;
    }

    
    @Column(name="REMARKS", length=240)
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    
    @Column(name="LOGO")
    public byte[] getLogo() {
        return this.logo;
    }
    
    public void setLogo(byte[] logo) {
        this.logo = logo;
    }




}


