package org.clinikraj.model;// default package
// Generated Oct 18, 2013 1:22:29 PM by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ContactModes generated by hbm2java
 */
@Entity
@Table(name="contact_modes"
    
)
public class ContactModes  implements java.io.Serializable {


     private Integer contactModeId;
     private String createdBy;
     private Date createdDate;
     private String lastUpdatedBy;
     private Date lastUpdatedDate;
     private String contactMode;
     private String activeFlag;

    public ContactModes() {
    }

    public ContactModes(String createdBy, Date createdDate, String lastUpdatedBy, Date lastUpdatedDate, String contactMode, String activeFlag) {
       this.createdBy = createdBy;
       this.createdDate = createdDate;
       this.lastUpdatedBy = lastUpdatedBy;
       this.lastUpdatedDate = lastUpdatedDate;
       this.contactMode = contactMode;
       this.activeFlag = activeFlag;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="CONTACT_MODE_ID", unique=true, nullable=false)
    public Integer getContactModeId() {
        return this.contactModeId;
    }
    
    public void setContactModeId(Integer contactModeId) {
        this.contactModeId = contactModeId;
    }

    
    @Column(name="CREATED_BY", nullable=false, length=60)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", nullable=false, length=19)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="LAST_UPDATED_BY", nullable=false, length=60)
    public String getLastUpdatedBy() {
        return this.lastUpdatedBy;
    }
    
    public void setLastUpdatedBy(String lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LAST_UPDATED_DATE", nullable=false, length=19)
    public Date getLastUpdatedDate() {
        return this.lastUpdatedDate;
    }
    
    public void setLastUpdatedDate(Date lastUpdatedDate) {
        this.lastUpdatedDate = lastUpdatedDate;
    }

    
    @Column(name="CONTACT_MODE", nullable=false)
    public String getContactMode() {
        return this.contactMode;
    }
    
    public void setContactMode(String contactMode) {
        this.contactMode = contactMode;
    }

    
    @Column(name="ACTIVE_FLAG", nullable=false, length=60)
    public String getActiveFlag() {
        return this.activeFlag;
    }
    
    public void setActiveFlag(String activeFlag) {
        this.activeFlag = activeFlag;
    }




}


