package org.clinikraj.model;// default package
// Generated Oct 18, 2013 1:22:29 PM by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DoctorCommisionRate generated by hbm2java
 */
@Entity
@Table(name="doctor_commision_rate"
    
)
public class DoctorCommisionRate  implements java.io.Serializable {


     private Integer doctorId;
     private Tests tests;
     private ClinicalLab clinicalLab;
     private String createdBy;
     private Date createdDate;
     private String lastUpdatedBy;
     private Date lastUpdatedDate;
     private Integer rate;
     private Date startDate;
     private Date endDate;
     private String activeFlag;
     private String deleteFlag;
     private String remarks;

    public DoctorCommisionRate() {
    }

	
    public DoctorCommisionRate(Tests tests, ClinicalLab clinicalLab, String createdBy, Date createdDate, String lastUpdatedBy, Date lastUpdatedDate) {
        this.tests = tests;
        this.clinicalLab = clinicalLab;
        this.createdBy = createdBy;
        this.createdDate = createdDate;
        this.lastUpdatedBy = lastUpdatedBy;
        this.lastUpdatedDate = lastUpdatedDate;
    }
    public DoctorCommisionRate(Tests tests, ClinicalLab clinicalLab, String createdBy, Date createdDate, String lastUpdatedBy, Date lastUpdatedDate, Integer rate, Date startDate, Date endDate, String activeFlag, String deleteFlag, String remarks) {
       this.tests = tests;
       this.clinicalLab = clinicalLab;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
       this.lastUpdatedBy = lastUpdatedBy;
       this.lastUpdatedDate = lastUpdatedDate;
       this.rate = rate;
       this.startDate = startDate;
       this.endDate = endDate;
       this.activeFlag = activeFlag;
       this.deleteFlag = deleteFlag;
       this.remarks = remarks;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="DOCTOR_ID", unique=true, nullable=false)
    public Integer getDoctorId() {
        return this.doctorId;
    }
    
    public void setDoctorId(Integer doctorId) {
        this.doctorId = doctorId;
    }


    @Column(name="TEST_ID", nullable=false)
    public Tests getTests() {
        return this.tests;
    }
    
    public void setTests(Tests tests) {
        this.tests = tests;
    }


    @Column(name="LAB_ID", nullable=false)
    public ClinicalLab getClinicalLab() {
        return this.clinicalLab;
    }
    
    public void setClinicalLab(ClinicalLab clinicalLab) {
        this.clinicalLab = clinicalLab;
    }

    
    @Column(name="CREATED_BY", nullable=false, length=60)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", nullable=false, length=19)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="LAST_UPDATED_BY", nullable=false, length=60)
    public String getLastUpdatedBy() {
        return this.lastUpdatedBy;
    }
    
    public void setLastUpdatedBy(String lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LAST_UPDATED_DATE", nullable=false, length=19)
    public Date getLastUpdatedDate() {
        return this.lastUpdatedDate;
    }
    
    public void setLastUpdatedDate(Date lastUpdatedDate) {
        this.lastUpdatedDate = lastUpdatedDate;
    }

    
    @Column(name="RATE")
    public Integer getRate() {
        return this.rate;
    }
    
    public void setRate(Integer rate) {
        this.rate = rate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="START_DATE", length=10)
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="END_DATE", length=10)
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    
    @Column(name="ACTIVE_FLAG", length=1)
    public String getActiveFlag() {
        return this.activeFlag;
    }
    
    public void setActiveFlag(String activeFlag) {
        this.activeFlag = activeFlag;
    }

    
    @Column(name="DELETE_FLAG", length=1)
    public String getDeleteFlag() {
        return this.deleteFlag;
    }
    
    public void setDeleteFlag(String deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    
    @Column(name="REMARKS", length=240)
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }




}


