package org.clinikraj.model;// default package
// Generated Oct 18, 2013 1:22:29 PM by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PatientTestOrders generated by hbm2java
 */
@Entity
@Table(name="patient_test_orders"
    
)
public class PatientTestOrders  implements java.io.Serializable {

	private String createdBy;
    private Date createdDate;
    private String lastUpdatedBy;
    private Date lastUpdatedDate;
    private Integer orderId;
	private Integer clinicalLab;
    private Integer patient;
	private Integer doctor;
    private Integer testVendor;
    private String publish;
     
    private String orderReference;
    private Date orderDate;
    private Integer grossAmount;
    private Integer discount;
    private Integer adavance;
    private Integer netAmount;
    private Integer balance;
    private Integer totalAmountCollected;
    private String activeFlag;
   private String deleteFlag;
	
     private String remarks;
     
    public PatientTestOrders() {
    }

	
    public PatientTestOrders(Integer patient, Integer clinicalLab, String createdBy, Date createdDate, String lastUpdatedBy, Date lastUpdatedDate) {
        this.patient = patient;
        this.clinicalLab = clinicalLab;
        this.createdBy = createdBy;
        this.createdDate = createdDate;
        this.lastUpdatedBy = lastUpdatedBy;
        this.lastUpdatedDate = lastUpdatedDate;
    }
    public PatientTestOrders(Integer patient, Integer testVendor, Integer clinicalLab, Integer doctor, String createdBy, Date createdDate, String lastUpdatedBy, Date lastUpdatedDate, String orderReference, Date orderDate, Integer grossAmount, Integer discount, Integer adavance, Integer netAmount, Integer balance, Integer totalAmountCollected, String remarks, Set patientTestGroupses, Set patientTestSubGroupses, Set patientTestses) {
       this.patient = patient;
       this.testVendor = testVendor;
       this.clinicalLab = clinicalLab;
       this.doctor = doctor;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
       this.lastUpdatedBy = lastUpdatedBy;
       this.lastUpdatedDate = lastUpdatedDate;
       this.orderReference = orderReference;
       this.orderDate = orderDate;
       this.grossAmount = grossAmount;
       this.discount = discount;
       this.adavance = adavance;
       this.netAmount = netAmount;
       this.balance = balance;
       this.totalAmountCollected = totalAmountCollected;
       
       this.remarks = remarks;
       
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ORDER_ID", unique=true, nullable=false)
    public Integer getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    @Column(name="PATIENT_ID", nullable=false)
    public Integer getPatient() {
        return this.patient;
    }
    
    public void setPatient(Integer patient) {
        this.patient = patient;
    }


    @Column(name="TEST_VENDOR_ID")
    public Integer getTestVendor() {
        return this.testVendor;
    }
    
    public void setTestVendor(Integer testVendor) {
        this.testVendor = testVendor;
    }

    @Column(name="LAB_ID", nullable=false)
    public Integer getClinicalLab() {
        return this.clinicalLab;
    }
    
    public void setClinicalLab(Integer clinicalLab) {
        this.clinicalLab = clinicalLab;
    }


    @Column(name="DOCTOR_ID")
    public Integer getDoctor() {
        return this.doctor;
    }
    
    public void setDoctor(Integer doctor) {
        this.doctor = doctor;
    }

    
    @Column(name="CREATED_BY", nullable=false, length=60)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", nullable=false, length=19)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="LAST_UPDATED_BY", nullable=false, length=60)
    public String getLastUpdatedBy() {
        return this.lastUpdatedBy;
    }
    
    public void setLastUpdatedBy(String lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LAST_UPDATED_DATE", nullable=false, length=19)
    public Date getLastUpdatedDate() {
        return this.lastUpdatedDate;
    }
    
    public void setLastUpdatedDate(Date lastUpdatedDate) {
        this.lastUpdatedDate = lastUpdatedDate;
    }

    
    @Column(name="ORDER_REFERENCE", length=60)
    public String getOrderReference() {
        return this.orderReference;
    }
    
    public void setOrderReference(String orderReference) {
        this.orderReference = orderReference;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="ORDER_DATE", length=10)
    public Date getOrderDate() {
        return this.orderDate;
    }
    
    public void setOrderDate(Date orderDate) {
        this.orderDate = orderDate;
    }

    
    @Column(name="GROSS_AMOUNT")
    public Integer getGrossAmount() {
        return this.grossAmount;
    }
    
    public void setGrossAmount(Integer grossAmount) {
        this.grossAmount = grossAmount;
    }

    
    @Column(name="DISCOUNT")
    public Integer getDiscount() {
        return this.discount;
    }
    
    public void setDiscount(Integer discount) {
        this.discount = discount;
    }

    
    @Column(name="ADAVANCE")
    public Integer getAdavance() {
        return this.adavance;
    }
    
    public void setAdavance(Integer adavance) {
        this.adavance = adavance;
    }

    
    @Column(name="NET_AMOUNT")
    public Integer getNetAmount() {
        return this.netAmount;
    }
    
    public void setNetAmount(Integer netAmount) {
        this.netAmount = netAmount;
    }

    
    @Column(name="BALANCE")
    public Integer getBalance() {
        return this.balance;
    }
    
    public void setBalance(Integer balance) {
        this.balance = balance;
    }

    @Column(name="TOTAL_AMOUNT_COLLECTED",length=10)
    public Integer getTotalAmountCollected() {
		return totalAmountCollected;
	}


	public void setTotalAmountCollected(Integer totalAmountCollected) {
		this.totalAmountCollected = totalAmountCollected;
	}

    

	@Column(name="REMARKS", length=240)
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

@Column(name="PUBLISH", length=1)
	public String getPublish() {
		return publish;
	}


	public void setPublish(String publish) {
		this.publish = publish;
	}

@Column(name="ACTIVE_FLAG", length=1)
	public String getActiveFlag() {
		return activeFlag;
	}


	public void setActiveFlag(String activeFlag) {
		this.activeFlag = activeFlag;
	}

@Column(name="DELETE_FLAG", length=1)
	public String getDeleteFlag() {
		return deleteFlag;
	}


	public void setDeleteFlag(String deleteFlag) {
		this.deleteFlag = deleteFlag;
	}






}


