package org.clinikraj.model;// default package
// Generated Oct 18, 2013 1:22:29 PM by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PatientTests generated by hbm2java
 */
@Entity
@Table(name="patient_tests"
    
)
public class PatientTests  implements java.io.Serializable {


     private Integer orderTestsId;
     
     private Integer testSubgroups;
     private Integer testGroups;
     private Integer tests;
     
     private Integer patientTestOrders;
    
     private String createdBy;
     private Date createdDate;
     private String lastUpdatedBy;
     private Date lastUpdatedDate;
     private int testRate;
     private Integer testJobNumber;
     private Date testStartDate;
     private Date testStartTime;
     private String testResult;
     private String specimenCollected;
     private String testResultApprovedBy;
     private String testAnalysisRemarks; 
     private String testBy; 
     private String testReference; 

    public PatientTests() {
    }

	
    public PatientTests(Integer testSubgroups, Integer testGroups, Integer tests, Integer patientTestOrders, String createdBy, Date createdDate, String lastUpdatedBy, Date lastUpdatedDate, int testRate, Date testStartTime, String testResultApprovedBy) {
        
        this.testSubgroups = testSubgroups;
        this.testGroups = testGroups;
        this.tests = tests;
        
        this.patientTestOrders = patientTestOrders;
        
        this.createdBy = createdBy;
        this.createdDate = createdDate;
        this.lastUpdatedBy = lastUpdatedBy;
        this.lastUpdatedDate = lastUpdatedDate;
        this.testRate = testRate;
        this.testStartTime = testStartTime;
        
        
        this.testResultApprovedBy = testResultApprovedBy;
    }
    public PatientTests(Integer testSubgroups, Integer testGroups, Integer tests, Integer patientTestOrders, String createdBy, Date createdDate, String lastUpdatedBy, Date lastUpdatedDate, int testRate, Integer testJobNumber, Date testStartDate, Date testStartTime, String testResult, String specimenCollected, String testResultApprovedBy,String testAnalysisRemarks,String testBy,String testReference) {
       
       this.testSubgroups = testSubgroups;
       this.testGroups = testGroups;
       this.tests = tests;
       
       this.patientTestOrders = patientTestOrders;
       
       this.createdBy = createdBy;
       this.createdDate = createdDate;
       this.lastUpdatedBy = lastUpdatedBy;
       this.lastUpdatedDate = lastUpdatedDate;
       this.testRate = testRate;
       this.testJobNumber = testJobNumber;
       this.testStartDate = testStartDate;
       this.testStartTime = testStartTime;
       this.testResult = testResult;
       
       this.specimenCollected = specimenCollected;
       this.testResultApprovedBy = testResultApprovedBy;
       this.testAnalysisRemarks = testAnalysisRemarks;
       this.testBy = testBy;
       this.testReference = testReference;
       
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ORDER_TESTS_ID", unique=true, nullable=false)
    public Integer getOrderTestsId() {
        return this.orderTestsId;
    }
    
    public void setOrderTestsId(Integer orderTestsId) {
        this.orderTestsId = orderTestsId;
    }


    

    @Column(name="TEST_SUBGROUP_ID", nullable=false)
    public Integer getTestSubgroups() {
        return this.testSubgroups;
    }
    
    public void setTestSubgroups(Integer testSubgroups) {
        this.testSubgroups = testSubgroups;
    }


    @Column(name="TEST_GROUP_ID", nullable=false)
    public Integer getTestGroups() {
        return this.testGroups;
    }
    
    public void setTestGroups(Integer testGroups) {
        this.testGroups = testGroups;
    }

    @Column(name="TEST_ID", nullable=false)
    public Integer getTests() {
        return this.tests;
    }
    
    public void setTests(Integer tests) {
        this.tests = tests;
    }


    


    @Column(name="ORDER_ID", nullable=false)
    public Integer getPatientTestOrders() {
        return this.patientTestOrders;
    }
    
    public void setPatientTestOrders(Integer patientTestOrders) {
        this.patientTestOrders = patientTestOrders;
    }


   

    
    @Column(name="CREATED_BY", nullable=false, length=60)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", nullable=false, length=19)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="LAST_UPDATED_BY", nullable=false, length=60)
    public String getLastUpdatedBy() {
        return this.lastUpdatedBy;
    }
    
    public void setLastUpdatedBy(String lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LAST_UPDATED_DATE", nullable=false, length=19)
    public Date getLastUpdatedDate() {
        return this.lastUpdatedDate;
    }
    
    public void setLastUpdatedDate(Date lastUpdatedDate) {
        this.lastUpdatedDate = lastUpdatedDate;
    }

    
    @Column(name="TEST_RATE", nullable=false)
    public int getTestRate() {
        return this.testRate;
    }
    
    public void setTestRate(int testRate) {
        this.testRate = testRate;
    }

    
    @Column(name="TEST_JOB_NUMBER")
    public Integer getTestJobNumber() {
        return this.testJobNumber;
    }
    
    public void setTestJobNumber(Integer testJobNumber) {
        this.testJobNumber = testJobNumber;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="TEST_START_DATE", length=10)
    public Date getTestStartDate() {
        return this.testStartDate;
    }
    
    public void setTestStartDate(Date testStartDate) {
        this.testStartDate = testStartDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="TEST_START_TIME",length=19)
    public Date getTestStartTime() {
        return this.testStartTime;
    }
    
    public void setTestStartTime(Date testStartTime) {
        this.testStartTime = testStartTime;
    }

    
    @Column(name="TEST_RESULT", length=120)
    public String getTestResult() {
        return this.testResult;
    }
    
    public void setTestResult(String testResult) {
        this.testResult = testResult;
    }

    
       
    @Column(name="SPECIMEN_COLLECTED", length=60)
    public String getSpecimenCollected() {
        return this.specimenCollected;
    }
    
    
    public void setSpecimenCollected(String specimenCollected) {
        this.specimenCollected = specimenCollected;
    }

    @Column(name="TEST_RESULT_APPROVED_BY", length=60)
	public String getTestResultApprovedBy() {
		return testResultApprovedBy;
	}


	public void setTestResultApprovedBy(String testResultApprovedBy) {
		this.testResultApprovedBy = testResultApprovedBy;
	}

	 @Column(name="TEST_ANALYSIS_REMARKS", length=120)
	public String getTestAnalysisRemarks() {
		return testAnalysisRemarks;
	}


	public void setTestAnalysisRemarks(String testAnalysisRemarks) {
		this.testAnalysisRemarks = testAnalysisRemarks;
	}

	@Column(name="TEST_BY", length=60)
	public String getTestBy() {
		return testBy;
	}


	public void setTestBy(String testBy) {
		this.testBy = testBy;
	}

	@Column(name="TEST_REFERENCE", length=20)
	public String getTestReference() {
		return testReference;
	}


	public void setTestReference(String testReference) {
		this.testReference = testReference;
	}

   




}


