package org.clinikraj.model;// default package
// Generated Oct 18, 2013 1:22:29 PM by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PatientTestGroups generated by hbm2java
 */
@Entity
@Table(name="patient_test_groups"
    
)
public class PatientTestGroups  implements java.io.Serializable {


     private Integer orderGroupId;
     private TestVendor testVendor;
     private TestGroups testGroups;
     private PatientTestOrders patientTestOrders;
     private String createdBy;
     private Date createdDate;
     private String lastUpdatedBy;
     private Date lastUpdatedDate;
    

    public PatientTestGroups() {
    }

	
    public PatientTestGroups(TestGroups testGroups, PatientTestOrders patientTestOrders, String createdBy, Date createdDate, String lastUpdatedBy, Date lastUpdatedDate) {
        this.testGroups = testGroups;
        this.patientTestOrders = patientTestOrders;
        this.createdBy = createdBy;
        this.createdDate = createdDate;
        this.lastUpdatedBy = lastUpdatedBy;
        this.lastUpdatedDate = lastUpdatedDate;
    }
    public PatientTestGroups(TestVendor testVendor, TestGroups testGroups, PatientTestOrders patientTestOrders, String createdBy, Date createdDate, String lastUpdatedBy, Date lastUpdatedDate, Set patientTestSubGroupses, Set patientTestses) {
       this.testVendor = testVendor;
       this.testGroups = testGroups;
       this.patientTestOrders = patientTestOrders;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
       this.lastUpdatedBy = lastUpdatedBy;
       this.lastUpdatedDate = lastUpdatedDate;
      
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ORDER_GROUP_ID", unique=true, nullable=false)
    public Integer getOrderGroupId() {
        return this.orderGroupId;
    }
    
    public void setOrderGroupId(Integer orderGroupId) {
        this.orderGroupId = orderGroupId;
    }


    @Column(name="TEST_VENDOR_ID")
    public TestVendor getTestVendor() {
        return this.testVendor;
    }
    
    public void setTestVendor(TestVendor testVendor) {
        this.testVendor = testVendor;
    }


    @Column(name="TEST_GROUP_ID", nullable=false)
    public TestGroups getTestGroups() {
        return this.testGroups;
    }
    
    public void setTestGroups(TestGroups testGroups) {
        this.testGroups = testGroups;
    }


    @Column(name="ORDER_ID", nullable=false)
    public PatientTestOrders getPatientTestOrders() {
        return this.patientTestOrders;
    }
    
    public void setPatientTestOrders(PatientTestOrders patientTestOrders) {
        this.patientTestOrders = patientTestOrders;
    }

    
    @Column(name="CREATED_BY", nullable=false, length=60)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", nullable=false, length=19)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="LAST_UPDATED_BY", nullable=false, length=60)
    public String getLastUpdatedBy() {
        return this.lastUpdatedBy;
    }
    
    public void setLastUpdatedBy(String lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LAST_UPDATED_DATE", nullable=false, length=19)
    public Date getLastUpdatedDate() {
        return this.lastUpdatedDate;
    }
    
    public void setLastUpdatedDate(Date lastUpdatedDate) {
        this.lastUpdatedDate = lastUpdatedDate;
    }






}


