package org.clinikraj.model;// default package
// Generated Oct 18, 2013 1:22:29 PM by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pintable generated by hbm2java
 */
@Entity
@Table(name="pintable"
   
)
public class Pintable  implements java.io.Serializable {


     private Integer pinId;
     private String createdBy;
     private Date createdDate;
     private String lastUpdatedBy;
     private Date lastUpdatedDate;
     private int postOfficeCode;
     private String city;
     private String district;
     private String state;
     private String country;

    public Pintable() {
    }

    public Pintable(String createdBy, Date createdDate, String lastUpdatedBy, Date lastUpdatedDate, int postOfficeCode, String city, String district, String state, String country) {
       this.createdBy = createdBy;
       this.createdDate = createdDate;
       this.lastUpdatedBy = lastUpdatedBy;
       this.lastUpdatedDate = lastUpdatedDate;
       this.postOfficeCode = postOfficeCode;
       this.city = city;
       this.district = district;
       this.state = state;
       this.country = country;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="PIN_ID", unique=true, nullable=false)
    public Integer getPinId() {
        return this.pinId;
    }
    
    public void setPinId(Integer pinId) {
        this.pinId = pinId;
    }

    
    @Column(name="CREATED_BY", nullable=false, length=60)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", nullable=false, length=19)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="LAST_UPDATED_BY", nullable=false, length=60)
    public String getLastUpdatedBy() {
        return this.lastUpdatedBy;
    }
    
    public void setLastUpdatedBy(String lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LAST_UPDATED_DATE", nullable=false, length=19)
    public Date getLastUpdatedDate() {
        return this.lastUpdatedDate;
    }
    
    public void setLastUpdatedDate(Date lastUpdatedDate) {
        this.lastUpdatedDate = lastUpdatedDate;
    }

    
    @Column(name="POST_OFFICE_CODE", nullable=false)
    public int getPostOfficeCode() {
        return this.postOfficeCode;
    }
    
    public void setPostOfficeCode(int postOfficeCode) {
        this.postOfficeCode = postOfficeCode;
    }

    
    @Column(name="CITY", nullable=false, length=60)
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }

    
    @Column(name="DISTRICT", nullable=false, length=60)
    public String getDistrict() {
        return this.district;
    }
    
    public void setDistrict(String district) {
        this.district = district;
    }

    
    @Column(name="STATE", nullable=false, length=60)
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }

    
    @Column(name="COUNTRY", nullable=false, length=60)
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }




}


