package org.clinikraj.model;// default package
// Generated Oct 18, 2013 1:22:29 PM by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * TestVendor generated by hbm2java
 */
@Entity
@Table(name="test_vendor"
    
    , uniqueConstraints = @UniqueConstraint(columnNames={"LAB_ID", "TEST_VENDOR_NAME"}) 
)
public class TestVendor  implements java.io.Serializable {


     private Integer testVendorId;
     private Integer clinicalLab;
     private String createdBy;
     private Date createdDate;
     private String lastUpdatedBy;
     private Date lastUpdatedDate;
     private String testVendorName;
     private String testVendorRegnNumber;
     private String tieUp;
     private String vendorContactName;
     private String emailId;
     private String alternateEmailId;
     private String addressLine1;
     private String addressLine2;
     private String area;
     private Integer postOfficeCode;
     private String city;
     private String district;
     private String state;
     private String country;
     private Long phoneLandline;
     private Long emergencyPhoneNumber;
     private Long phoneMobile;
     private Long phoneFax;
     private Date startDate;
     private Date endDate;
     private String activeFlag;
     private String deleteFlag;
     private String preferredContactMethod;
     private String smsAlerts;
     private String remarks;
     

    public TestVendor() {
    }

	
    public TestVendor(Integer clinicalLab, String createdBy, Date createdDate, String lastUpdatedBy, Date lastUpdatedDate, String testVendorName, Date startDate) {
        this.clinicalLab = clinicalLab;
        this.createdBy = createdBy;
        this.createdDate = createdDate;
        this.lastUpdatedBy = lastUpdatedBy;
        this.lastUpdatedDate = lastUpdatedDate;
        this.testVendorName = testVendorName;
        this.startDate = startDate;
    }
    public TestVendor(Integer clinicalLab, String createdBy, Date createdDate, String lastUpdatedBy, Date lastUpdatedDate, String testVendorName, String testVendorRegnNumber, String tieUp, String vendorContactName, String emailId, String alternateEmailId, String addressLine1, String addressLine2, String area, Integer postOfficeCode, String city, String district, String state, String country, Long phoneLandline, Long emergencyPhoneNumber, Long phoneMobile, Long phoneFax, Date startDate, Date endDate, String activeFlag, String deleteFlag, String preferredContactMethod, String smsAlerts, String remarks, Set patientTestGroupses, Set patientTestOrderses, Set testGroupses, Set patientTestses, Set patientTestSubGroupses) {
       this.clinicalLab = clinicalLab;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
       this.lastUpdatedBy = lastUpdatedBy;
       this.lastUpdatedDate = lastUpdatedDate;
       this.testVendorName = testVendorName;
       this.testVendorRegnNumber = testVendorRegnNumber;
       this.tieUp = tieUp;
       this.vendorContactName = vendorContactName;
       this.emailId = emailId;
       this.alternateEmailId = alternateEmailId;
       this.addressLine1 = addressLine1;
       this.addressLine2 = addressLine2;
       this.area = area;
       this.postOfficeCode = postOfficeCode;
       this.city = city;
       this.district = district;
       this.state = state;
       this.country = country;
       this.phoneLandline = phoneLandline;
       this.emergencyPhoneNumber = emergencyPhoneNumber;
       this.phoneMobile = phoneMobile;
       this.phoneFax = phoneFax;
       this.startDate = startDate;
       this.endDate = endDate;
       this.activeFlag = activeFlag;
       this.deleteFlag = deleteFlag;
       this.preferredContactMethod = preferredContactMethod;
       this.smsAlerts = smsAlerts;
       this.remarks = remarks;
       
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="TEST_VENDOR_ID", unique=true, nullable=false)
    public Integer getTestVendorId() {
        return this.testVendorId;
    }
    
    public void setTestVendorId(Integer testVendorId) {
        this.testVendorId = testVendorId;
    }


    @Column(name="LAB_ID", nullable=false)
    public Integer getClinicalLab() {
        return this.clinicalLab;
    }
    
    public void setClinicalLab(Integer clinicalLab) {
        this.clinicalLab = clinicalLab;
    }

    
    @Column(name="CREATED_BY", nullable=false, length=60)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", nullable=false, length=19)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="LAST_UPDATED_BY", nullable=false, length=60)
    public String getLastUpdatedBy() {
        return this.lastUpdatedBy;
    }
    
    public void setLastUpdatedBy(String lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LAST_UPDATED_DATE", nullable=false, length=19)
    public Date getLastUpdatedDate() {
        return this.lastUpdatedDate;
    }
    
    public void setLastUpdatedDate(Date lastUpdatedDate) {
        this.lastUpdatedDate = lastUpdatedDate;
    }

    
    @Column(name="TEST_VENDOR_NAME", nullable=false, length=60)
    public String getTestVendorName() {
        return this.testVendorName;
    }
    
    public void setTestVendorName(String testVendorName) {
        this.testVendorName = testVendorName;
    }

    
    @Column(name="TEST_VENDOR_REGN_NUMBER", length=60)
    public String getTestVendorRegnNumber() {
        return this.testVendorRegnNumber;
    }
    
    public void setTestVendorRegnNumber(String testVendorRegnNumber) {
        this.testVendorRegnNumber = testVendorRegnNumber;
    }

    
    @Column(name="TIE_UP", length=1)
    public String getTieUp() {
        return this.tieUp;
    }
    
    public void setTieUp(String tieUp) {
        this.tieUp = tieUp;
    }

    
    @Column(name="VENDOR_CONTACT_NAME", length=120)
    public String getVendorContactName() {
        return this.vendorContactName;
    }
    
    public void setVendorContactName(String vendorContactName) {
        this.vendorContactName = vendorContactName;
    }

    
    @Column(name="EMAIL_ID", length=100)
    public String getEmailId() {
        return this.emailId;
    }
    
    public void setEmailId(String emailId) {
        this.emailId = emailId;
    }

    
    @Column(name="ALTERNATE_EMAIL_ID", length=100)
    public String getAlternateEmailId() {
        return this.alternateEmailId;
    }
    
    public void setAlternateEmailId(String alternateEmailId) {
        this.alternateEmailId = alternateEmailId;
    }

    
    @Column(name="ADDRESS_LINE1", length=60)
    public String getAddressLine1() {
        return this.addressLine1;
    }
    
    public void setAddressLine1(String addressLine1) {
        this.addressLine1 = addressLine1;
    }

    
    @Column(name="ADDRESS_LINE2", length=60)
    public String getAddressLine2() {
        return this.addressLine2;
    }
    
    public void setAddressLine2(String addressLine2) {
        this.addressLine2 = addressLine2;
    }

    
    @Column(name="AREA", length=60)
    public String getArea() {
        return this.area;
    }
    
    public void setArea(String area) {
        this.area = area;
    }

    
    @Column(name="POST_OFFICE_CODE")
    public Integer getPostOfficeCode() {
        return this.postOfficeCode;
    }
    
    public void setPostOfficeCode(Integer postOfficeCode) {
        this.postOfficeCode = postOfficeCode;
    }

    
    @Column(name="CITY", length=60)
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }

    
    @Column(name="DISTRICT", length=60)
    public String getDistrict() {
        return this.district;
    }
    
    public void setDistrict(String district) {
        this.district = district;
    }

    
    @Column(name="STATE", length=60)
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }

    
    @Column(name="COUNTRY", length=60)
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }

    
    @Column(name="PHONE_LANDLINE")
    public Long getPhoneLandline() {
        return this.phoneLandline;
    }
    
    public void setPhoneLandline(Long phoneLandline) {
        this.phoneLandline = phoneLandline;
    }

    
    @Column(name="EMERGENCY_PHONE_NUMBER")
    public Long getEmergencyPhoneNumber() {
        return this.emergencyPhoneNumber;
    }
    
    public void setEmergencyPhoneNumber(Long emergencyPhoneNumber) {
        this.emergencyPhoneNumber = emergencyPhoneNumber;
    }

    
    @Column(name="PHONE_MOBILE")
    public Long getPhoneMobile() {
        return this.phoneMobile;
    }
    
    public void setPhoneMobile(Long phoneMobile) {
        this.phoneMobile = phoneMobile;
    }

    
    @Column(name="PHONE_FAX")
    public Long getPhoneFax() {
        return this.phoneFax;
    }
    
    public void setPhoneFax(Long phoneFax) {
        this.phoneFax = phoneFax;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="START_DATE", nullable=false, length=10)
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="END_DATE", length=10)
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    
    @Column(name="ACTIVE_FLAG", length=1)
    public String getActiveFlag() {
        return this.activeFlag;
    }
    
    public void setActiveFlag(String activeFlag) {
        this.activeFlag = activeFlag;
    }

    
    @Column(name="DELETE_FLAG", length=1)
    public String getDeleteFlag() {
        return this.deleteFlag;
    }
    
    public void setDeleteFlag(String deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    
    @Column(name="PREFERRED_CONTACT_METHOD", length=30)
    public String getPreferredContactMethod() {
        return this.preferredContactMethod;
    }
    
    public void setPreferredContactMethod(String preferredContactMethod) {
        this.preferredContactMethod = preferredContactMethod;
    }

    
    @Column(name="SMS_ALERTS", length=1)
    public String getSmsAlerts() {
        return this.smsAlerts;
    }
    
    public void setSmsAlerts(String smsAlerts) {
        this.smsAlerts = smsAlerts;
    }

    
    @Column(name="REMARKS", length=240)
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }




}


