package org.clinikraj.model;
// Generated Oct 18, 2013 1:22:29 PM by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tests generated by hbm2java
 */
@Entity
@Table(name="tests"
    
)
public class Tests  implements java.io.Serializable {


     private Integer testId;
     private TestGroups testGroups;
     private TestSubgroups testSubgroups;
     private ClinicalLab clinicalLab;
     private String createdBy;
     private Date createdDate;
     private String lastUpdatedBy;
     private Date lastUpdatedDate;
     private Integer rate;
     private Integer defaultDeliveryDays;
     private Date startDate;
     private Date endDate;
     private String activeFlag;
     private String testName;
     private String description;
     private String remarks;
     private String specimenType;
     
    public Tests() {
    }

	
    public Tests(TestGroups testGroups, TestSubgroups testSubgroups, ClinicalLab clinicalLab, String createdBy, Date createdDate, String lastUpdatedBy, Date lastUpdatedDate, int rate, String testName) {
        this.testGroups = testGroups;
        this.testSubgroups = testSubgroups;
        this.clinicalLab = clinicalLab;
        this.createdBy = createdBy;
        this.createdDate = createdDate;
        this.lastUpdatedBy = lastUpdatedBy;
        this.lastUpdatedDate = lastUpdatedDate;
        this.rate = rate;
        this.testName = testName;
    }
    public Tests(TestGroups testGroups, TestSubgroups testSubgroups, ClinicalLab clinicalLab, String createdBy, Date createdDate, String lastUpdatedBy, Date lastUpdatedDate, int rate, Integer defaultDeliveryDays, Date startDate, Date endDate, String activeFlag, String testName, String description, String remarks, Set doctorCommisionRates, Set patientTestses) {
       this.testGroups = testGroups;
       this.testSubgroups = testSubgroups;
       this.clinicalLab = clinicalLab;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
       this.lastUpdatedBy = lastUpdatedBy;
       this.lastUpdatedDate = lastUpdatedDate;
       this.rate = rate;
       this.defaultDeliveryDays = defaultDeliveryDays;
       this.startDate = startDate;
       this.endDate = endDate;
       this.activeFlag = activeFlag;
       this.testName = testName;
       this.description = description;
       this.remarks = remarks;
      
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="TEST_ID", unique=true, nullable=false)
    public Integer getTestId() {
        return this.testId;
    }
    
    public void setTestId(Integer testId) {
        this.testId = testId;
    }


    @Column(name="TEST_GROUP_ID", nullable=false)
    public TestGroups getTestGroups() {
        return this.testGroups;
    }
    
    public void setTestGroups(TestGroups testGroups) {
        this.testGroups = testGroups;
    }


    @Column(name="TEST_SUBGROUP_ID", nullable=false)
    public TestSubgroups getTestSubgroups() {
        return this.testSubgroups;
    }
    
    public void setTestSubgroups(TestSubgroups testSubgroups) {
        this.testSubgroups = testSubgroups;
    }


    @Column(name="LAB_ID", nullable=false)
    public ClinicalLab getClinicalLab() {
        return this.clinicalLab;
    }
    
    public void setClinicalLab(ClinicalLab clinicalLab) {
        this.clinicalLab = clinicalLab;
    }

    
    @Column(name="CREATED_BY", nullable=false, length=60)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", nullable=false, length=19)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="LAST_UPDATED_BY", nullable=false, length=60)
    public String getLastUpdatedBy() {
        return this.lastUpdatedBy;
    }
    
    public void setLastUpdatedBy(String lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LAST_UPDATED_DATE", nullable=false, length=19)
    public Date getLastUpdatedDate() {
        return this.lastUpdatedDate;
    }
    
    public void setLastUpdatedDate(Date lastUpdatedDate) {
        this.lastUpdatedDate = lastUpdatedDate;
    }

    
    @Column(name="ORDER_RATE", nullable=false)
    public Integer getRate() {
        return this.rate;
    }
    
    public void setRate(Integer rate) {
        this.rate = rate;
    }

    
    @Column(name="DEFAULT_DELIVERY_DAYS")
    public Integer getDefaultDeliveryDays() {
        return this.defaultDeliveryDays;
    }
    
    public void setDefaultDeliveryDays(Integer defaultDeliveryDays) {
        this.defaultDeliveryDays = defaultDeliveryDays;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="START_DATE", length=10)
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="END_DATE", length=10)
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    
    @Column(name="ACTIVE_FLAG", length=1)
    public String getActiveFlag() {
        return this.activeFlag;
    }
    
    public void setActiveFlag(String activeFlag) {
        this.activeFlag = activeFlag;
    }

    
    @Column(name="TEST_NAME", nullable=false, length=60)
    public String getTestName() {
        return this.testName;
    }
    
    public void setTestName(String testName) {
        this.testName = testName;
    }

    
    @Column(name="DESCRIPTION", length=120)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="REMARKS", length=120)
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    @Column(name="SPECIMEN_TYPE", length=60)
	public String getSpecimenType() {
		return specimenType;
	}


	public void setSpecimenType(String specimenType) {
		this.specimenType = specimenType;
	}






}


