package org.clinikraj.model;// default package
// Generated Oct 18, 2013 1:22:29 PM by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TestSubgroups generated by hbm2java
 */
@Entity
@Table(name="test_subgroups"
   
)
public class TestSubgroups  implements java.io.Serializable {


     private Integer testSubgroupId;
     private TestGroups testGroups;
     private ClinicalLab clinicalLab;
     private String createdBy;
     private Date createdDate;
     private String lastUpdatedBy;
     private Date lastUpdatedDate;
     private String testSubgroupName;
     private String descrption;
     private String remarks;
     

    public TestSubgroups() {
    }

	
    public TestSubgroups(TestGroups testGroups, ClinicalLab clinicalLab, String createdBy, Date createdDate, String lastUpdatedBy, Date lastUpdatedDate, String testSubgroupName) {
        this.testGroups = testGroups;
        this.clinicalLab = clinicalLab;
        this.createdBy = createdBy;
        this.createdDate = createdDate;
        this.lastUpdatedBy = lastUpdatedBy;
        this.lastUpdatedDate = lastUpdatedDate;
        this.testSubgroupName = testSubgroupName;
    }
    public TestSubgroups(TestGroups testGroups, ClinicalLab clinicalLab, String createdBy, Date createdDate, String lastUpdatedBy, Date lastUpdatedDate, String testSubgroupName, String descrption, String remarks, Set testses, Set patientTestses, Set patientTestSubGroupses, Set testNormalRangeses) {
       this.testGroups = testGroups;
       this.clinicalLab = clinicalLab;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
       this.lastUpdatedBy = lastUpdatedBy;
       this.lastUpdatedDate = lastUpdatedDate;
       this.testSubgroupName = testSubgroupName;
       this.descrption = descrption;
       this.remarks = remarks;
      
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="TEST_SUBGROUP_ID", unique=true, nullable=false)
    public Integer getTestSubgroupId() {
        return this.testSubgroupId;
    }
    
    public void setTestSubgroupId(Integer testSubgroupId) {
        this.testSubgroupId = testSubgroupId;
    }


    @Column(name="TEST_GROUP_ID", nullable=false)
    public TestGroups getTestGroups() {
        return this.testGroups;
    }
    
    public void setTestGroups(TestGroups testGroups) {
        this.testGroups = testGroups;
    }


    @Column(name="LAB_ID", nullable=false)
    public ClinicalLab getClinicalLab() {
        return this.clinicalLab;
    }
    
    public void setClinicalLab(ClinicalLab clinicalLab) {
        this.clinicalLab = clinicalLab;
    }

    
    @Column(name="CREATED_BY", nullable=false, length=60)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", nullable=false, length=19)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="LAST_UPDATED_BY", nullable=false, length=60)
    public String getLastUpdatedBy() {
        return this.lastUpdatedBy;
    }
    
    public void setLastUpdatedBy(String lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LAST_UPDATED_DATE", nullable=false, length=19)
    public Date getLastUpdatedDate() {
        return this.lastUpdatedDate;
    }
    
    public void setLastUpdatedDate(Date lastUpdatedDate) {
        this.lastUpdatedDate = lastUpdatedDate;
    }

    
    @Column(name="TEST_SUBGROUP_NAME", nullable=false, length=60)
    public String getTestSubgroupName() {
        return this.testSubgroupName;
    }
    
    public void setTestSubgroupName(String testSubgroupName) {
        this.testSubgroupName = testSubgroupName;
    }

    
    @Column(name="DESCRPTION", length=120)
    public String getDescrption() {
        return this.descrption;
    }
    
    public void setDescrption(String descrption) {
        this.descrption = descrption;
    }

    
    @Column(name="REMARKS", length=120)
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }





}


