package org.clinikraj.model;
// Generated Oct 18, 2013 1:22:29 PM by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TestNormalRanges generated by hbm2java
 */
@Entity
@Table(name="test_normal_ranges"
    
)
public class TestNormalRanges  implements java.io.Serializable {


     private Integer testId;
     private TestGroups testGroups;
     private TestSubgroups testSubgroups;
     private ClinicalLab clinicalLab;
     private String createdBy;
     private Date createdDate;
     private String lastUpdatedBy;
     private Date lastUpdatedDate;
     private String specimenType;
     private String specimenUom;
     private String specimenConditions;
     private String sex;
     private int ageMin;
     private int ageMax;
     private String normalRangeLow;
     private String normalRangeHigh;

    public TestNormalRanges() {
    }

	
    public TestNormalRanges(TestGroups testGroups, TestSubgroups testSubgroups, ClinicalLab clinicalLab, String createdBy, Date createdDate, String lastUpdatedBy, Date lastUpdatedDate, String specimenType, String sex, int ageMin, int ageMax, String normalRangeLow, String normalRangeHigh) {
        this.testGroups = testGroups;
        this.testSubgroups = testSubgroups;
        this.clinicalLab = clinicalLab;
        this.createdBy = createdBy;
        this.createdDate = createdDate;
        this.lastUpdatedBy = lastUpdatedBy;
        this.lastUpdatedDate = lastUpdatedDate;
        this.specimenType = specimenType;
        this.sex = sex;
        this.ageMin = ageMin;
        this.ageMax = ageMax;
        this.normalRangeLow = normalRangeLow;
        this.normalRangeHigh = normalRangeHigh;
    }
    public TestNormalRanges(TestGroups testGroups, TestSubgroups testSubgroups, ClinicalLab clinicalLab, String createdBy, Date createdDate, String lastUpdatedBy, Date lastUpdatedDate, String specimenType, String specimenUom, String specimenConditions, String sex, int ageMin, int ageMax, String normalRangeLow, String normalRangeHigh) {
       this.testGroups = testGroups;
       this.testSubgroups = testSubgroups;
       this.clinicalLab = clinicalLab;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
       this.lastUpdatedBy = lastUpdatedBy;
       this.lastUpdatedDate = lastUpdatedDate;
       this.specimenType = specimenType;
       this.specimenUom = specimenUom;
       this.specimenConditions = specimenConditions;
       this.sex = sex;
       this.ageMin = ageMin;
       this.ageMax = ageMax;
       this.normalRangeLow = normalRangeLow;
       this.normalRangeHigh = normalRangeHigh;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="TEST_ID", unique=true, nullable=false)
    public Integer getTestId() {
        return this.testId;
    }
    
    public void setTestId(Integer testId) {
        this.testId = testId;
    }


    @Column(name="TEST_GROUP_ID", nullable=false)
    public TestGroups getTestGroups() {
        return this.testGroups;
    }
    
    public void setTestGroups(TestGroups testGroups) {
        this.testGroups = testGroups;
    }


    @Column(name="TEST_SUBGROUP_ID", nullable=false)
    public TestSubgroups getTestSubgroups() {
        return this.testSubgroups;
    }
    
    public void setTestSubgroups(TestSubgroups testSubgroups) {
        this.testSubgroups = testSubgroups;
    }


    @Column(name="LAB_ID", nullable=false)
    public ClinicalLab getClinicalLab() {
        return this.clinicalLab;
    }
    
    public void setClinicalLab(ClinicalLab clinicalLab) {
        this.clinicalLab = clinicalLab;
    }

    
    @Column(name="CREATED_BY", nullable=false, length=60)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", nullable=false, length=19)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="LAST_UPDATED_BY", nullable=false, length=60)
    public String getLastUpdatedBy() {
        return this.lastUpdatedBy;
    }
    
    public void setLastUpdatedBy(String lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LAST_UPDATED_DATE", nullable=false, length=19)
    public Date getLastUpdatedDate() {
        return this.lastUpdatedDate;
    }
    
    public void setLastUpdatedDate(Date lastUpdatedDate) {
        this.lastUpdatedDate = lastUpdatedDate;
    }

    
    @Column(name="SPECIMEN_TYPE", nullable=false, length=60)
    public String getSpecimenType() {
        return this.specimenType;
    }
    
    public void setSpecimenType(String specimenType) {
        this.specimenType = specimenType;
    }

    
    @Column(name="SPECIMEN_UOM", length=60)
    public String getSpecimenUom() {
        return this.specimenUom;
    }
    
    public void setSpecimenUom(String specimenUom) {
        this.specimenUom = specimenUom;
    }

    
    @Column(name="SPECIMEN_CONDITIONS", length=60)
    public String getSpecimenConditions() {
        return this.specimenConditions;
    }
    
    public void setSpecimenConditions(String specimenConditions) {
        this.specimenConditions = specimenConditions;
    }

    
    @Column(name="SEX", nullable=false, length=10)
    public String getSex() {
        return this.sex;
    }
    
    public void setSex(String sex) {
        this.sex = sex;
    }

    
    @Column(name="AGE_MIN", nullable=false)
    public int getAgeMin() {
        return this.ageMin;
    }
    
    public void setAgeMin(int ageMin) {
        this.ageMin = ageMin;
    }

    
    @Column(name="AGE_MAX", nullable=false)
    public int getAgeMax() {
        return this.ageMax;
    }
    
    public void setAgeMax(int ageMax) {
        this.ageMax = ageMax;
    }

    
    @Column(name="NORMAL_RANGE_LOW", nullable=false, length=20)
    public String getNormalRangeLow() {
        return this.normalRangeLow;
    }
    
    public void setNormalRangeLow(String normalRangeLow) {
        this.normalRangeLow = normalRangeLow;
    }

    
    @Column(name="NORMAL_RANGE_HIGH", nullable=false, length=20)
    public String getNormalRangeHigh() {
        return this.normalRangeHigh;
    }
    
    public void setNormalRangeHigh(String normalRangeHigh) {
        this.normalRangeHigh = normalRangeHigh;
    }




}


