package org.clinikraj.model;// default package
// Generated Oct 18, 2013 1:22:29 PM by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TestGroups generated by hbm2java
 */
@Entity
@Table(name="test_groups"
    
)
public class TestGroups  implements java.io.Serializable {


     private Integer testGroupId;
     private TestVendor testVendor;
     private ClinicalLab clinicalLab;
     private String createdBy;
     private Date createdDate;
     private String lastUpdatedBy;
     private Date lastUpdatedDate;
     private String testGroupName;
     private String description;
     private String remarks;
     
    public TestGroups() {
    }

	
    public TestGroups(ClinicalLab clinicalLab, String createdBy, Date createdDate, String lastUpdatedBy, Date lastUpdatedDate, String testGroupName) {
        this.clinicalLab = clinicalLab;
        this.createdBy = createdBy;
        this.createdDate = createdDate;
        this.lastUpdatedBy = lastUpdatedBy;
        this.lastUpdatedDate = lastUpdatedDate;
        this.testGroupName = testGroupName;
    }
    public TestGroups(TestVendor testVendor, ClinicalLab clinicalLab, String createdBy, Date createdDate, String lastUpdatedBy, Date lastUpdatedDate, String testGroupName, String description, String remarks, Set testses, Set patientTestSubGroupses, Set testSubgroupses, Set patientTestses, Set testNormalRangeses, Set patientTestGroupses) {
       this.testVendor = testVendor;
       this.clinicalLab = clinicalLab;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
       this.lastUpdatedBy = lastUpdatedBy;
       this.lastUpdatedDate = lastUpdatedDate;
       this.testGroupName = testGroupName;
       this.description = description;
       this.remarks = remarks;
      
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="TEST_GROUP_ID", unique=true, nullable=false)
    public Integer getTestGroupId() {
        return this.testGroupId;
    }
    
    public void setTestGroupId(Integer testGroupId) {
        this.testGroupId = testGroupId;
    }


    @Column(name="TEST_VENDOR_ID")
    public TestVendor getTestVendor() {
        return this.testVendor;
    }
    
    public void setTestVendor(TestVendor testVendor) {
        this.testVendor = testVendor;
    }


    @Column(name="LAB_ID", nullable=false)
    public ClinicalLab getClinicalLab() {
        return this.clinicalLab;
    }
    
    public void setClinicalLab(ClinicalLab clinicalLab) {
        this.clinicalLab = clinicalLab;
    }

    
    @Column(name="CREATED_BY", nullable=false, length=60)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", nullable=false, length=19)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="LAST_UPDATED_BY", nullable=false, length=60)
    public String getLastUpdatedBy() {
        return this.lastUpdatedBy;
    }
    
    public void setLastUpdatedBy(String lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LAST_UPDATED_DATE", nullable=false, length=19)
    public Date getLastUpdatedDate() {
        return this.lastUpdatedDate;
    }
    
    public void setLastUpdatedDate(Date lastUpdatedDate) {
        this.lastUpdatedDate = lastUpdatedDate;
    }

    
    @Column(name="TEST_GROUP_NAME", nullable=false, length=60)
    public String getTestGroupName() {
        return this.testGroupName;
    }
    
    public void setTestGroupName(String testGroupName) {
        this.testGroupName = testGroupName;
    }

    
    @Column(name="DESCRIPTION", length=120)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="REMARKS", length=120)
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }



}


