package org.clinikraj.model;// default package
// Generated Oct 18, 2013 1:22:29 PM by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Uom generated by hbm2java
 */
@Entity
@Table(name="uom"
   
)
public class Uom  implements java.io.Serializable {


     private Integer uomId;
     private String createdBy;
     private Date createdDate;
     private String lastUpdatedBy;
     private Date lastUpdatedDate;
     private int unitOfMeasure;
     private String descrption;

    public Uom() {
    }

    public Uom(String createdBy, Date createdDate, String lastUpdatedBy, Date lastUpdatedDate, int unitOfMeasure, String descrption) {
       this.createdBy = createdBy;
       this.createdDate = createdDate;
       this.lastUpdatedBy = lastUpdatedBy;
       this.lastUpdatedDate = lastUpdatedDate;
       this.unitOfMeasure = unitOfMeasure;
       this.descrption = descrption;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="UOM_ID", unique=true, nullable=false)
    public Integer getUomId() {
        return this.uomId;
    }
    
    public void setUomId(Integer uomId) {
        this.uomId = uomId;
    }

    
    @Column(name="CREATED_BY", nullable=false, length=60)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", nullable=false, length=19)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="LAST_UPDATED_BY", nullable=false, length=60)
    public String getLastUpdatedBy() {
        return this.lastUpdatedBy;
    }
    
    public void setLastUpdatedBy(String lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LAST_UPDATED_DATE", nullable=false, length=19)
    public Date getLastUpdatedDate() {
        return this.lastUpdatedDate;
    }
    
    public void setLastUpdatedDate(Date lastUpdatedDate) {
        this.lastUpdatedDate = lastUpdatedDate;
    }

    
    @Column(name="UNIT_OF_MEASURE", nullable=false)
    public int getUnitOfMeasure() {
        return this.unitOfMeasure;
    }
    
    public void setUnitOfMeasure(int unitOfMeasure) {
        this.unitOfMeasure = unitOfMeasure;
    }

    
    @Column(name="DESCRPTION", nullable=false, length=120)
    public String getDescrption() {
        return this.descrption;
    }
    
    public void setDescrption(String descrption) {
        this.descrption = descrption;
    }




}


