package org.clinikraj.model;// default package
// Generated Oct 18, 2013 1:22:29 PM by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name="user"
   
    , uniqueConstraints = @UniqueConstraint(columnNames={"LAB_ID", "USER_NAME"}) 
)
public class User  implements java.io.Serializable {


     private Integer userId;
     private Integer clinicalLab;
     private String createdBy;
     private Date createdDate;
     private String lastUpdatedBy;
     private Date lastUpdatedDate;
     private Integer sessionId;
     private String userName;
     private String userType;
     private Integer referenceId;
     private String role;
     private String password;
     private String defaultPasswordChanged;
     private String passwordQuestion1;
     private String passwordAnswer1;
     private String passwordQuestion2;
     private String passwordAnswer2;
     private String passwordQuestion3;
     private String passwordAnswer3;
     private String deleteFlag;
     private String activeFlag;
     private Date startDate;
     private Date endDate;
     private Date lastSuccessLoginDate;
     private Date lastFailedLoginDate;
     private Date nextPasswordChangeDate;
     private String remarks;
     private String firstLogin;
    

    public User() {
    }

	
    public User(Integer clinicalLab, String createdBy, Date createdDate, String lastUpdatedBy, Date lastUpdatedDate, String userName, String userType, String role, String password, String defaultPasswordChanged, String passwordQuestion1, String passwordAnswer1, String passwordQuestion2, String passwordAnswer2, String passwordQuestion3, String passwordAnswer3, Date startDate, Date lastSuccessLoginDate, Date lastFailedLoginDate) {
        this.clinicalLab = clinicalLab;
        this.createdBy = createdBy;
        this.createdDate = createdDate;
        this.lastUpdatedBy = lastUpdatedBy;
        this.lastUpdatedDate = lastUpdatedDate;
        this.userName = userName;
        this.userType = userType;
        this.role = role;
        this.password = password;
        this.defaultPasswordChanged = defaultPasswordChanged;
        this.passwordQuestion1 = passwordQuestion1;
        this.passwordAnswer1 = passwordAnswer1;
        this.passwordQuestion2 = passwordQuestion2;
        this.passwordAnswer2 = passwordAnswer2;
        this.passwordQuestion3 = passwordQuestion3;
        this.passwordAnswer3 = passwordAnswer3;
        this.startDate = startDate;
        this.lastSuccessLoginDate = lastSuccessLoginDate;
        this.lastFailedLoginDate = lastFailedLoginDate;
    }

    public User(Integer clinicalLab, String createdBy, Date createdDate, String lastUpdatedBy, Date lastUpdatedDate, Integer sessionId, String userName, String userType, Integer referenceId, String role, String password, String defaultPasswordChanged, String passwordQuestion1, String passwordAnswer1, String passwordQuestion2, String passwordAnswer2, String passwordQuestion3, String passwordAnswer3, String deleteFlag, String activeFlag, Date startDate, Date endDate, Date lastSuccessLoginDate, Date lastFailedLoginDate, Date nextPasswordChangeDate, String remarks, String firstLogin) {

       this.clinicalLab = clinicalLab;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
       this.lastUpdatedBy = lastUpdatedBy;
       this.lastUpdatedDate = lastUpdatedDate;
       this.sessionId = sessionId;
       this.userName = userName;
       this.userType = userType;
       this.referenceId = referenceId;
       this.role = role;
       this.password = password;
       this.defaultPasswordChanged = defaultPasswordChanged;
       this.passwordQuestion1 = passwordQuestion1;
       this.passwordAnswer1 = passwordAnswer1;
       this.passwordQuestion2 = passwordQuestion2;
       this.passwordAnswer2 = passwordAnswer2;
       this.passwordQuestion3 = passwordQuestion3;
       this.passwordAnswer3 = passwordAnswer3;
       this.deleteFlag = deleteFlag;
       this.activeFlag = activeFlag;
       this.startDate = startDate;
       this.endDate = endDate;
       this.lastSuccessLoginDate = lastSuccessLoginDate;
       this.lastFailedLoginDate = lastFailedLoginDate;
       this.nextPasswordChangeDate = nextPasswordChangeDate;
       this.remarks = remarks;
       this.firstLogin = firstLogin;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="USER_ID", unique=true, nullable=false)
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }


    @Column(name="LAB_ID", nullable=false)
    public Integer getClinicalLab() {
        return this.clinicalLab;
    }
    
    public void setClinicalLab(Integer clinicalLab) {
        this.clinicalLab = clinicalLab;
    }

    
    @Column(name="CREATED_BY", nullable=false, length=60)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", nullable=false, length=19)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="LAST_UPDATED_BY", nullable=false, length=60)
    public String getLastUpdatedBy() {
        return this.lastUpdatedBy;
    }
    
    public void setLastUpdatedBy(String lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LAST_UPDATED_DATE", nullable=false, length=19)
    public Date getLastUpdatedDate() {
        return this.lastUpdatedDate;
    }
    
    public void setLastUpdatedDate(Date lastUpdatedDate) {
        this.lastUpdatedDate = lastUpdatedDate;
    }

    
    @Column(name="SESSION_ID", length=100)
    public Integer getSessionId() {
        return this.sessionId;
    }
    
    public void setSessionId(Integer sessionId) {
        this.sessionId = sessionId;
    }

    
    @Column(name="USER_NAME", nullable=false, length=60)
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }

    
    @Column(name="USER_TYPE", nullable=false, length=60)
    public String getUserType() {
        return this.userType;
    }
    
    public void setUserType(String userType) {
        this.userType = userType;
    }

    
    @Column(name="REFERENCE_ID")
    public Integer getReferenceId() {
        return this.referenceId;
    }
    
    public void setReferenceId(Integer referenceId) {
        this.referenceId = referenceId;
    }

    
    @Column(name="ROLE", nullable=false, length=60)
    public String getRole() {
        return this.role;
    }
    
    public void setRole(String role) {
        this.role = role;
    }

    
    @Column(name="PASSWORD", nullable=false, length=60)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="DEFAULT_PASSWORD_CHANGED", nullable=false, length=1)
    public String getDefaultPasswordChanged() {
        return this.defaultPasswordChanged;
    }
    
    public void setDefaultPasswordChanged(String defaultPasswordChanged) {
        this.defaultPasswordChanged = defaultPasswordChanged;
    }

    
    @Column(name="PASSWORD_QUESTION1", nullable=false, length=60)
    public String getPasswordQuestion1() {
        return this.passwordQuestion1;
    }
    
    public void setPasswordQuestion1(String passwordQuestion1) {
        this.passwordQuestion1 = passwordQuestion1;
    }

    
    @Column(name="PASSWORD_ANSWER1", nullable=false, length=60)
    public String getPasswordAnswer1() {
        return this.passwordAnswer1;
    }
    
    public void setPasswordAnswer1(String passwordAnswer1) {
        this.passwordAnswer1 = passwordAnswer1;
    }

    
    @Column(name="PASSWORD_QUESTION2", nullable=false, length=60)
    public String getPasswordQuestion2() {
        return this.passwordQuestion2;
    }
    
    public void setPasswordQuestion2(String passwordQuestion2) {
        this.passwordQuestion2 = passwordQuestion2;
    }

    
    @Column(name="PASSWORD_ANSWER2", nullable=false, length=60)
    public String getPasswordAnswer2() {
        return this.passwordAnswer2;
    }
    
    public void setPasswordAnswer2(String passwordAnswer2) {
        this.passwordAnswer2 = passwordAnswer2;
    }

    
    @Column(name="PASSWORD_QUESTION3", nullable=false, length=60)
    public String getPasswordQuestion3() {
        return this.passwordQuestion3;
    }
    
    public void setPasswordQuestion3(String passwordQuestion3) {
        this.passwordQuestion3 = passwordQuestion3;
    }

    
    @Column(name="PASSWORD_ANSWER3", nullable=false, length=60)
    public String getPasswordAnswer3() {
        return this.passwordAnswer3;
    }
    
    public void setPasswordAnswer3(String passwordAnswer3) {
        this.passwordAnswer3 = passwordAnswer3;
    }

    
    @Column(name="DELETE_FLAG", length=1)
    public String getDeleteFlag() {
        return this.deleteFlag;
    }
    
    public void setDeleteFlag(String deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    
    @Column(name="ACTIVE_FLAG", length=1)
    public String getActiveFlag() {
        return this.activeFlag;
    }
    
    public void setActiveFlag(String activeFlag) {
        this.activeFlag = activeFlag;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="START_DATE", nullable=false, length=10)
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="END_DATE", length=10)
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LAST_SUCCESS_LOGIN_DATE", nullable=false, length=19)
    public Date getLastSuccessLoginDate() {
        return this.lastSuccessLoginDate;
    }
    
    public void setLastSuccessLoginDate(Date lastSuccessLoginDate) {
        this.lastSuccessLoginDate = lastSuccessLoginDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LAST_FAILED_LOGIN_DATE", nullable=false, length=19)
    public Date getLastFailedLoginDate() {
        return this.lastFailedLoginDate;
    }
    
    public void setLastFailedLoginDate(Date lastFailedLoginDate) {
        this.lastFailedLoginDate = lastFailedLoginDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="NEXT_PASSWORD_CHANGE_DATE", length=10)
    public Date getNextPasswordChangeDate() {
        return this.nextPasswordChangeDate;
    }
    
    public void setNextPasswordChangeDate(Date nextPasswordChangeDate) {
        this.nextPasswordChangeDate = nextPasswordChangeDate;
    }

    
    @Column(name="REMARKS", length=240)
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    @Column(name="FIRST_LOGIN", length=1)
	public String getFirstLogin() {
		return firstLogin;
	}


	public void setFirstLogin(String firstLogin) {
		this.firstLogin = firstLogin;
	}

}


